name: CI / Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile & test
        run: |
          npx hardhat compile
          npx hardhat test

  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Slither
        run: |
          sudo apt-get update && sudo apt-get install python3-pip -y
          pip3 install slither-analyzer

      - name: Run Slither
        run: slither contracts/WethArbitrageDynamic.sol
